apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-shared-configmap-asm-1-20
  namespace: aks-istio-system
data:
  mesh: |-
    accessLogFile: /dev/stdout
    defaultConfig:
      holdApplicationUntilProxyStarts: true
